"""Added created_at field for all tables

Revision ID: b0ef71fbac6b
Revises: 1bba6510a779
Create Date: 2019-10-20 11:02:43.131465

"""
from alembic import op, context
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b0ef71fbac6b"
down_revision = "1bba6510a779"
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memberships", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column(
        "mood_templates", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column("moods", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column(
        "team_member_moods", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column("team_roles", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("teams", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    op.drop_column("teams", "created_at")
    op.drop_column("team_roles", "created_at")
    op.drop_column("team_member_moods", "created_at")
    op.drop_column("moods", "created_at")
    op.drop_column("mood_templates", "created_at")
    op.drop_column("memberships", "created_at")
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
